Republish dht keys
EspressoSystems/HotShot pull request #1532
Opened 2023-08-09 13:37 UTC by DieracDelta

By default, republish DHT keys every 8 hours and set expiry for every 4 days. Enable these values as configuration options by the networking layer. Closes #1531

2023-08-09 13:54 UTC, elliedavidson approved these changes
lgtm!

2023-08-10 15:31 UTC, shenkeyao requested changes
Looks good, except for a comment about the `ttl` setting.

2023-08-14 12:06 UTC, DieracDelta commented on libp2p-networking/src/network/node.rs
> +            );
Oooops! Yes! I had a separate field for this.

2023-08-14 14:22 UTC, elliedavidson approved these changes

2023-08-14 17:51 UTC, shenkeyao approved these changes

2023-08-14 19:59 UTC, merged