Add unit test for DA task
EspressoSystems/HotShot pull request #1590
Opened 2023-08-21 19:57 UTC by shenkeyao

Add a unit test for the DA task, to test the handling of proposal, vote and view change events.

TODO: remove `build_da_api` and move `build_consensus_api` to a separate file to be shared by all unit tests, after https://github.com/EspressoSystems/HotShot/pull/1565 is merged.

Closes https://github.com/EspressoSystems/HotShot/issues/1493.

2023-08-21 22:35 UTC, elliedavidson requested changes
Just the one typo

2023-08-21 22:35 UTC, elliedavidson commented on task-impls/src/da.rs
> +                // `self.cur_view` should be at least 1 since there is a view change before getting
Good comment!

2023-08-21 22:35 UTC, elliedavidson commented on testing/tests/consensus_task.rs
> +// use hotshot::traits::implementations::MemoryCommChannefl;
Is this a typo? :)

2023-08-21 22:57 UTC, shenkeyao commented on testing/tests/consensus_task.rs
> +// use hotshot::traits::implementations::MemoryCommChannefl;
Yes, fixed!

2023-08-22 12:24 UTC, elliedavidson submitted a review, later dismissed

2023-08-22 18:52 UTC, elliedavidson approved these changes

2023-08-22 18:59 UTC, merged