Cancel polling for retrieved items
EspressoSystems/HotShot pull request #2031
Opened 2023-11-09 20:09 UTC by rob-maron

2023-11-10 19:48 UTC, shenkeyao submitted a review, later dismissed
LGTM!

2023-11-10 21:40 UTC, bfish713 requested changes

2023-11-10 21:40 UTC, bfish713 commented on crates/task-impls/src/consensus.rs
> +                self.quorum_exchange
I don't think we can cancel the DAC poll here.  Usually the DAC comes before the proposal, but it isn't always the case.  We should Cancel the DAC polling on the DAC received event

2023-11-10 23:10 UTC, shenkeyao approved these changes

2023-11-13 18:15 UTC, bfish713 approved these changes

2023-11-14 18:26 UTC, merged