[VALIDATED_STATE] - Add state information to the `Decide` event
EspressoSystems/HotShot pull request #2733
Opened 2024-03-08 17:48 UTC by shenkeyao

Closes https://github.com/EspressoSystems/HotShot/issues/2695.

### This PR: 
* Creates an application-specific `StateDelta` type and adds its test impl.
* Adds `StateDelta` to be an associated type of `ValidatedState`.
* Updates `ValidatedState::validate_and_apply_header` and `::genesis` to return the state delta as well.
* Adds the state and state delta to the leaf chain in the `Decide` event and the saved view.

### Key places to review: 
* `crates/example-types/src/state_types.rs`.

2024-03-08 17:59 UTC, shenkeyao commented
I'm going to send an update to wrap the fields in `Event` into `Arc`.

2024-03-09 00:59 UTC, shenkeyao commented on crates/task-impls/src/consensus.rs
> +                                state_delta: Arc::new(state_delta),
Sounds good! I've moved the state and delta to the leaf chain.

2024-03-09 00:59 UTC, shenkeyao commented on crates/types/src/traits/states.rs
> +    Clone + Serialize + DeserializeOwned + Debug + Default + Hash + PartialEq + Eq + Send + Sync
Fixed! I missed some places when adding `Arc` so `Clone` was needed, but it's not anymore.

2024-03-11 13:33 UTC, jbearer reviewed
Thanks @shenkeyao! Logic looks good I think. I had one code cleanliness comment then I think this is good

2024-03-11 13:33 UTC, jbearer commented on crates/types/src/event.rs
> +    Option<VidDisperse<TYPES>>,
This tuple is getting unwieldy, let's make a struct for it

2024-03-12 14:09 UTC, jbearer approved these changes

2024-03-12 16:11 UTC, imabdulbasit approved these changes

2024-03-12 16:12 UTC, imabdulbasit requested changes
merge conflicts

2024-03-12 16:17 UTC, shenkeyao commented
@imabdulbasit @jbearer Some files in `hotshot` were moved to a new `hotshot-types` repo. I'm going to fix the conflicts due to this.

2024-03-12 20:20 UTC, imabdulbasit approved these changes

2024-03-12 20:22 UTC, merged