Tj/typos and ordering
EspressoSystems/HotShot pull request #3524
Opened 2024-07-31 22:23 UTC by 0xkato

### This PR: 
Non-issues from the review.

Correcting typos, variable ordering and removing some superfluous code.

2024-07-31 22:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/EspressoSystems/HotShot?pullRequest=3524) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/EspressoSystems/HotShot?pullRequest=3524) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/EspressoSystems/HotShot?pullRequest=3524) it.</sub>

2024-08-01 17:02 UTC, jparr721 approved these changes

2024-08-01 17:43 UTC, bfish713 requested changes
Looks like there is a lint failure, can you fix that? and then this should be good to do

2024-08-01 20:08 UTC, jparr721 approved these changes

2024-08-02 14:56 UTC, bfish713 approved these changes

2024-08-02 15:20 UTC, merged