Remove unused config stuff
EspressoSystems/HotShot pull request #3771
Opened 2024-10-18 15:04 UTC by bfish713

Closes #<ISSUE_NUMBER>

### This PR: 

### This PR does not: 

### Key places to review:

2024-10-28 17:58 UTC, ss-es approved these changes
looks good to me, just one question

2024-10-28 17:58 UTC, ss-es commented on crates/hotshot/src/traits/networking/libp2p_network.rs
> -
Is the intention that everyone is always receiving all DA broadcasts/gossip?

2024-10-28 18:02 UTC, ss-es requested changes
oh, wait -- it looks like the PR broke `tests_3` somehow

feel free to dismiss

2024-10-29 14:39 UTC, bfish713 commented
Figured out test 3, basically the byzantine test for bad proposals is not great in general.  The network task effectively blocks us from sending the multiple bad proposals out.  The reason this PR broke it is because I removed round start delay which changed the timing such that the byzantine node blocks it's own proposal because it thinks it's a duplicate action.  I fixed this by adding more nodes so that we have enough honest leaders to complete 50 other views in time.  I feel like the byzantine leader timing out is totally a reasonable expectation but lmk if you think otherwise

2024-10-29 15:30 UTC, ss-es approved these changes

2024-10-29 18:45 UTC, merged