Move most of utils out into separate crates
EspressoSystems/HotShot pull request #784
Opened 2022-11-29 04:16 UTC by DieracDelta

2022-11-29 19:39 UTC, Ancient123 submitted a review, later dismissed

2022-11-29 20:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/EspressoSystems/HotShot?pullRequest=784) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/EspressoSystems/HotShot?pullRequest=784) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/EspressoSystems/HotShot?pullRequest=784) it.</sub>

2022-11-29 20:20 UTC, Ancient123 commented
> [![CLA assistant check](https://camo.githubusercontent.com/4c970efeed75dd01f6778bf7e33dec85e4171375cb69acb0927bfc9d437d78d9/68747470733a2f2f636c612d617373697374616e742e696f2f70756c6c2f62616467652f6e6f745f7369676e6564)](https://cla-assistant.io/EspressoSystems/HotShot?pullRequest=784) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/EspressoSystems/HotShot?pullRequest=784) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/EspressoSystems/HotShot?pullRequest=784) it.

I think CLA bot is bugging out. Because it should bypass for people in the EspressoSystems org.

2022-11-29 21:17 UTC, DieracDelta commented
Looks like CLA is fixed. CI should pass now, so we can probably merge this.

2022-11-29 23:49 UTC, shenkeyao requested changes
LGTM except for a typo.

2022-11-29 23:49 UTC, shenkeyao commented on libp2p-networking/README.md
> +Networking library inteded for use with HotShot. Builds upon compatibilitys on libp2p-rs.
Typo, compatibilities or compatibility?

2022-11-30 00:01 UTC, shenkeyao approved these changes

2022-11-30 00:05 UTC, merged